//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOPW.Alarm.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOPW.Alarm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   https://www.gopw.kr/patchnote.txt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Address_PatchnoteString {
            get {
                return ResourceManager.GetString("Address_PatchnoteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://gopw.kr/GOPW_Alarm.exe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Address_UpdateTarget {
            get {
                return ResourceManager.GetString("Address_UpdateTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.gopw.kr/version.txt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Address_Versionstring {
            get {
                return ResourceManager.GetString("Address_Versionstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Cancel_Text {
            get {
                return ResourceManager.GetString("Button_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Close_Text {
            get {
                return ResourceManager.GetString("Button_Close_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Confirm_Text {
            get {
                return ResourceManager.GetString("Button_Confirm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   패치 노트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Patchnote_Text {
            get {
                return ResourceManager.GetString("Button_Patchnote_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Update_Text {
            get {
                return ResourceManager.GetString("Button_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마지막 경보기는 삭제할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_Delete_Last_Alert {
            get {
                return ResourceManager.GetString("Error_Cannot_Delete_Last_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///    경보기 실행 실패. 지정된 클라이언트를 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Cannot_Find_Selected_Client {
            get {
                return ResourceManager.GetString("Error_Cannot_Find_Selected_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Error {
            get {
                return ResourceManager.GetString("Error_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스캔 주기는 반드시 숫자여야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_interval_must_be_number {
            get {
                return ResourceManager.GetString("Error_interval_must_be_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경보기 이름은 공백이 될 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Scaner_Name_Cannot_be_empty {
            get {
                return ResourceManager.GetString("Error_Scaner_Name_Cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경보기 이름엔 |, #이 들어갈 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_Scaner_Name_Cannot_include_special_letter {
            get {
                return ResourceManager.GetString("Error_Scaner_Name_Cannot_include_special_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream과(와) 유사한 System.IO.UnmanagedMemoryStream 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Eve_warning_hull {
            get {
                return ResourceManager.GetStream("Eve_warning_hull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 버전 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CurrentVersion {
            get {
                return ResourceManager.GetString("Label_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최신 버전 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_LatestVersion {
            get {
                return ResourceManager.GetString("Label_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   여기를 클릭하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Click_Here {
            get {
                return ResourceManager.GetString("Message_Click_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이브 온라인 클라이언트가 최소화 상태입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_EVE_Client_Is_min_stat {
            get {
                return ResourceManager.GetString("Message_EVE_Client_Is_min_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로운 버전의 고퓨 알람을 사용할 수 있습니다. 업데이트 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_NewVerAvailAlert {
            get {
                return ResourceManager.GetString("Message_NewVerAvailAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이브 온라인 클라이언트를 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Please_Select_EVE_Client {
            get {
                return ResourceManager.GetString("Message_Please_Select_EVE_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경보기의 종류를 선택해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Please_Select_Type_Of_Scaner {
            get {
                return ResourceManager.GetString("Message_Please_Select_Type_Of_Scaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 종료된 경보기입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Scaner_Already_Ended {
            get {
                return ResourceManager.GetString("Message_Scaner_Already_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경보기가 이미 켜져있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Scaner_Already_Running {
            get {
                return ResourceManager.GetString("Message_Scaner_Already_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap standing_bad {
            get {
                object obj = ResourceManager.GetObject("standing_bad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap standing_neut {
            get {
                object obj = ResourceManager.GetObject("standing_neut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap standing_terrible {
            get {
                object obj = ResourceManager.GetObject("standing_terrible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap standing_war {
            get {
                object obj = ResourceManager.GetObject("standing_war", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   기타 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_AlertData {
            get {
                return ResourceManager.GetString("Text_AlertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영역 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Area_Setting {
            get {
                return ResourceManager.GetString("Text_Area_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Dot {
            get {
                return ResourceManager.GetString("Text_Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Empty {
            get {
                return ResourceManager.GetString("Text_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimized과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Minimized {
            get {
                return ResourceManager.GetString("Text_Minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NeutScaned과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_NeutScaned {
            get {
                return ResourceManager.GetString("Text_NeutScaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waveform audio format|*.WAV과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_OFD_Filter {
            get {
                return ResourceManager.GetString("Text_OFD_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   패치 노트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_PatchNote {
            get {
                return ResourceManager.GetString("Text_PatchNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   prepare과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_prepare {
            get {
                return ResourceManager.GetString("Text_prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Reset {
            get {
                return ResourceManager.GetString("Text_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경보기 좌표과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Scaner_Coordnate {
            get {
                return ResourceManager.GetString("Text_Scaner_Coordnate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   캐릭터 명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Scaner_EVE_Char_Name {
            get {
                return ResourceManager.GetString("Text_Scaner_EVE_Char_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경보기 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Scaner_name {
            get {
                return ResourceManager.GetString("Text_Scaner_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경보 파일 위치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Scaner_Sound_File_location {
            get {
                return ResourceManager.GetString("Text_Scaner_Sound_File_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경보기 종류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Scaner_type {
            get {
                return ResourceManager.GetString("Text_Scaner_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   neut과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Scaner_type_neut {
            get {
                return ResourceManager.GetString("Text_Scaner_type_neut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Scaner_type_rat {
            get {
                return ResourceManager.GetString("Text_Scaner_type_rat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   reload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Scaner_type_reload {
            get {
                return ResourceManager.GetString("Text_Scaner_type_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클라이언트 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Select_Cilent {
            get {
                return ResourceManager.GetString("Text_Select_Cilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Space {
            get {
                return ResourceManager.GetString("Text_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   고퓨 경보기 업데이트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_UpdateAsk_name {
            get {
                return ResourceManager.GetString("Text_UpdateAsk_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working.. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Working {
            get {
                return ResourceManager.GetString("Text_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Working_2 {
            get {
                return ResourceManager.GetString("Text_Working_2", resourceCulture);
            }
        }
    }
}
